%% Extract the features from each swing

load('angles_proSLlace_2_proc.mat')
load('angles_TourSBoa2_proc.mat')
load('angles_free2_proc.mat')
load('angles_ProBoa2_proc.mat')
load('angles_tourLace2_proc.mat')
load('angles_freeBoa2_proc.mat')

angles = angles_TourSBoa2_proc %Select one at a time

%% Start with max and min joint angles

output = horzcat(max(angles.lAnkle.AB,[],2),min(angles.lAnkle.AB,[],2),max(angles.lAnkle.DORSI,[],2),min(angles.lAnkle.DORSI,[],2),...
    max(angles.lAnkle.INT,[],2),min(angles.lAnkle.INT,[],2),max(angles.rAnkle.AB,[],2),min(angles.rAnkle.AB,[],2),max(angles.rAnkle.DORSI,[],2),...
    min(angles.rAnkle.DORSI,[],2),max(angles.rAnkle.INT,[],2),min(angles.rAnkle.INT,[],2), max(angles.lKnee.AB,[],2),...
    min(angles.lKnee.AB,[],2),max(angles.lKnee.FLEX,[],2),min(angles.lKnee.FLEX,[],2),max(angles.lKnee.INT,[],2),...
    min(angles.lKnee.INT,[],2),max(angles.rKnee.AB,[],2),min(angles.rKnee.AB,[],2),max(angles.rKnee.FLEX,[],2),...
    min(angles.rKnee.FLEX,[],2),max(angles.rKnee.INT,[],2),min(angles.rKnee.INT,[],2), max(angles.lHip.AB,[],2),...
    min(angles.lHip.AB,[],2),max(angles.lHip.FLEX,[],2),min(angles.lHip.FLEX,[],2),max(angles.lHip.INT,[],2),...
    min(angles.lHip.INT,[],2),max(angles.rHip.AB,[],2),min(angles.rHip.AB,[],2),max(angles.rHip.FLEX,[],2),...
    min(angles.rHip.FLEX,[],2),max(angles.rHip.INT,[],2),min(angles.rHip.INT,[],2))

